const express = require("express");
const router = express.Router();

const authRoutes = require("./AuthRoutes");
const paymentRoutes = require("./PaymentRoutes");
const webhookRoutes = require("./WebhookRoutes");
const courseRoutes = require("./CourseRoutes");
const courseVideoRoutes = require("./CourseVideoRoutes");
const systemRoutes = require("./SystemRoutes");
const videoRoutes = require("./VideosRoutes");
const CertificateRoutes = require("./CertificateRoutes");
const ProgressCourseRoutes = require("./ProgressCourseRoutes");
const CommunityRoutes = require("./CommunityRoutes");
const UserRoutes = require("./UserRoutes");
const adminRoutes = require("./AdminRoutes");
const EventRoutes = require("./EventRoutes");
const TicketRoutes = require("./TicketRoutes");
const ProductRoutes = require("./ProductsRoutes");
const CartRoutes = require("./CartRoutes");
const OrderRoutes = require("./OrderRoutes");
const OrderPaymentRoutes = require("./OrderPaymentRoutes");
const StripeRoutes = require("./StripeRoutes");
const AddressRoutes = require("./AddressRoutes");
const LivesRoutes = require("./LiveRoutes");
const { testIvsConfig, getToken } = require("../../generateToken");
router.use("/auth", authRoutes);
router.use("/payment", paymentRoutes);
router.use("/webhook", webhookRoutes);
router.use("/courses", courseRoutes);
router.use("/course-video", courseVideoRoutes);
router.use("/systems", systemRoutes);
router.use("/videos", videoRoutes);
router.use("/certificate", CertificateRoutes);
router.use("/progress-video", ProgressCourseRoutes);
router.use("/community", CommunityRoutes);
router.use("/user", UserRoutes);
router.use("/admin", adminRoutes);
router.use("/events", EventRoutes);
router.use("/tickets", TicketRoutes);
router.use("/products", ProductRoutes);
router.use("/cart", CartRoutes);
router.use("/orders", OrderRoutes);
router.use("/order-payments", OrderPaymentRoutes);
router.use("/stripe", StripeRoutes);
router.use("/address", AddressRoutes);
router.use("/lives", LivesRoutes);
router.get("/generate-token-ivs", getToken);
router.get("/test-config-ivs", testIvsConfig);
module.exports = router;
