const express = require("express");
const router = express.Router();

const authRoutes = require("./AuthRoutes");
const paymentRoutes = require("./PaymentRoutes");
const webhookRoutes = require("./WebhookRoutes");
const courseRoutes = require("./CourseRoutes");
const courseVideoRoutes = require("./CourseVideoRoutes");
const systemRoutes = require("./SystemRoutes");
const videoRoutes = require("./VideosRoutes");
const CertificateRoutes = require("./CertificateRoutes");
const ProgressCourseRoutes = require("./ProgressCourseRoutes");
const CommunityRoutes = require("./CommunityRoutes");
const UserRoutes = require("./UserRoutes");
const adminRoutes = require("./AdminRoutes");
const EventRoutes = require("./EventRoutes");
const TicketRoutes = require("./TicketRoutes");
const ProductRoutes = require("./ProductsRoutes");
const CartRoutes = require("./CartRoutes");
const OrderRoutes = require("./OrderRoutes");
const OrderPaymentRoutes = require("./OrderPaymentRoutes");
const StripeRoutes = require("./StripeRoutes");
const AddressRoutes = require("./AddressRoutes");
const LivesRoutes = require("./LiveRoutes");
const PostRoutes = require("./PostRoutes");
const { testIvsConfig, getToken } = require("../../generateToken");
const saveNotificationToken = require("../controllers/PushNotificationsFirebase");
const { authMiddleware } = require("../middlewares/authMiddleware");
const NotificationsRoutes = require("./NotificationsRoutes");
const CertificationsRoutes = require("./CertificationRoutes");
const ModuleCertificationRoutes = require("./ModuleCertificationRoutes");
const CriterionModuleCertificationRoutes = require("./ModuleCriterionCertificationRoute");
const ModuleSubmissionCertificationRoutes = require("./ModuleSubmissionCertificationRoute");
const ModileEvaluationSubmitionCertificationRoutes = require("./ModuleEvaluationCertificationRoutes");
const BillingRoutes = require("./BillingRoutes");
const StoreRoutes = require("./StoreRoutes");
const FormationRoutes = require("./FormationRoutes");
const ModuleFormationsRoutes = require("./ModuleFormationsRoutes");
const SubscriptionRoutes = require("./SubscriptionRoutes");
const { getLiveChatToken } = require("../controllers/LiveChatController");
const MessagesRoutes = require("./MessageRoutes");
router.use("/auth", authRoutes);
router.use("/payment", paymentRoutes);
router.use("/webhook", webhookRoutes);
router.use("/courses", courseRoutes);
router.use("/course-video", courseVideoRoutes);
router.use("/systems", systemRoutes);
router.use("/videos", videoRoutes);
router.use("/certificate", CertificateRoutes);
router.use("/progress-video", ProgressCourseRoutes);
router.use("/community", CommunityRoutes);
router.use("/user", UserRoutes);
router.use("/admin", adminRoutes);
router.use("/events", EventRoutes);
router.use("/tickets", TicketRoutes);
router.use("/products", ProductRoutes);
router.use("/cart", CartRoutes);
router.use("/orders", OrderRoutes);
router.use("/order-payments", OrderPaymentRoutes);
router.use("/stripe", StripeRoutes);
router.use("/address", AddressRoutes);
router.use("/lives", LivesRoutes);
router.use("/posts", PostRoutes);
router.get("/generate-token-ivs", getToken);
router.get("/test-config-ivs", testIvsConfig);
router.post("/save-notification-token", authMiddleware, saveNotificationToken);
router.post("/lives/chat-token", authMiddleware, getLiveChatToken);
router.use("/notifications", NotificationsRoutes);
router.use("/certifications", CertificationsRoutes);
router.use("/module-certifications", ModuleCertificationRoutes);
router.use("/module-criterion", CriterionModuleCertificationRoutes);
router.use("/module-submission", ModuleSubmissionCertificationRoutes);
router.use("/module-evaluation", ModileEvaluationSubmitionCertificationRoutes);
router.use("/billing", BillingRoutes);
router.use("/stores", StoreRoutes);
router.use("/formations", FormationRoutes);
router.use("/module-formations", ModuleFormationsRoutes);
router.use("/subscriptions", SubscriptionRoutes);
router.use("/messages", MessagesRoutes);

module.exports = router;
